; ESP8266 NodeMCU Weather Station
; Author: Alexandr Kazakov
; Created: 07.05.2026

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino

monitor_speed = 115200
upload_speed = 115200 

lib_deps =
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
    paulstoffregen/OneWire @ ^2.3.8
    milesburton/DallasTemperature @ ^3.11.0
    adafruit/RTClib @ ^2.1.4
    arduino-libraries/NTPClient @ ^3.2.1
